-- Generated by nwg-displays on 2026-08-04 at 23:58:57. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@240.0",
    position = "0x0",
    scale = 1.0,
})
hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@165.0",
    position = "1920x0",
    scale = 1.0
})
