#!/usr/bin/env bash
set -euo pipefail
shopt -s nullglob

ESP="/boot"
ENTRY_DIR="$ESP/loader/entries"
OUTPUT="$ESP/EFI/nixos/grub-direct.cfg"

mkdir -p "$(dirname "$OUTPUT")"

entries=("$ENTRY_DIR"/nixos-generation-*.conf)

if ((${#entries[@]} == 0)); then
    echo "No NixOS generation entries found in $ENTRY_DIR" >&2
    exit 1
fi

temporary="$(mktemp "$OUTPUT.tmp.XXXXXX")"

{
    echo '# Automatically generated by NixOS.'
    echo 'set default=0'
    echo 'set timeout=10'
    echo

    printf '%s\n' "${entries[@]}" |
    sort -Vr |
    while IFS= read -r entry; do
        generation="${entry##*nixos-generation-}"
        generation="${generation%.conf}"

        title="$(
            sed -n 's/^title[[:space:]]*//p' "$entry" |
            head -n1
        )"

        linux="$(
            sed -n 's/^linux[[:space:]]*//p' "$entry" |
            head -n1
        )"

        options="$(
            sed -n 's/^options[[:space:]]*//p' "$entry" |
            head -n1
        )"

        mapfile -t initrds < <(
            sed -n 's/^initrd[[:space:]]*//p' "$entry"
        )

        [[ -n "$linux" ]] || continue

        title="${title//\"/\'}"

        printf 'menuentry "NixOS Generation %s — %s (automatic)" {\n' \
            "$generation" "$title"

        echo '    insmod part_gpt'
        echo '    insmod fat'

        printf \
          '    search --no-floppy --file --set=nixesp %s\n' \
          "$linux"

        printf \
          '    linux ($nixesp)%s %s\n' \
          "$linux" "$options"

        if ((${#initrds[@]})); then
            printf '    initrd'

            for initrd in "${initrds[@]}"; do
                printf ' ($nixesp)%s' "$initrd"
            done

            printf '\n'
        fi

        echo '}'
        echo
    done
} > "$temporary"

chmod 0644 "$temporary"
mv -f "$temporary" "$OUTPUT"

echo "Generated $OUTPUT"
